### ISSUE TITLE
Use custom type as parameter to test

### ISSUE THREAD

**Issue by anders-alma** [VSoftTechnologies/DUnitX#164] opened 2016-10-24 14:57 UTC
Using this:
type TMyType = (valueA, valueB);
and using valueA as a string in the parameter to a testcase works fine.

But if you change the type declaration to
type TMyType = (valueA = 1, valueB = 2);
the test doesn't run at all....

Seems lika a bug to me :-)

/Anders

**Comment by rlove** [comment] 2016-10-24 15:47
This is due to limitation in the delphi RTTI and is not a bug in DUnitX

Number enumerated types are not accessible to RTTI.
https://quality.embarcadero.com/browse/RSP-12189

**Comment by anders-alma** [comment] 2016-10-24 19:07
That is probably so, yes. But couldn't DUnitX say something, not just silently ignore the whole testcase?

/Anders

**Comment by vincentparrett** [comment] 2017-03-23 03:09
I'm open to suggestions on how to fix this, we currently have no way of dealing with this that I can think of.

**Comment by vincentparrett** [comment] 2019-11-04 22:46
Closing as there is currently (up to delphi 10.3.x so far) no way to resolve this.

**Closed by vincentparrett** 2019-11-04 22:46 UTC
Labels: Compiler Bug, RTTI Bug
