### ISSUE TITLE
Passing floating point values through TestCase-Attribute fails

### ISSUE THREAD

**Issue by codejanovic** [VSoftTechnologies/DUnitX#108] opened 2015-02-19 16:30 UTC
Hi folks,

Passing floating point numbers within the given TestCase-Attribute fails. I do pass them this way:
```delphi
[TestCase('Test1', '6, 5.44,0.0001')]
procedure TestFloat(const AGiven: Double; const AExpected: Double; const ATolerance: Double);
```

DUnitX converts the Arguments as listed:
AGiven = 6
AExpected = 0
ATolerance = 0

After debugging, i found that the following piece of Code (Unit DunitX.Utils) does not work for me (XE6):
```delphi
function ConvStr2Float
.....
AResult := TValue.FromFloat(ATarget, StrToFloatDef(ASource.AsString, 0));
......
```
Instead of Returning the correct floating point number, it returns the default (0).
Is there anything I do wrong? Passing TFormatSettings manually (and initializing the Decimalseparator) to StrToFloat() works fine instead.

Kind Regards,
Aleks

**Comment by sglienke** [comment] 2015-03-25 09:01
This code is from DSharp originally where it is locale specific. In the context of DUnitX however you might want to pass a TFormatSettings with a dot as decimal separator. ConvStr2Float and probably other methods should be modified accordingly.

**Comment by altembo** [comment] 2015-06-16 14:51
Yes, but I think there should also be also a dunitx-wide formatsetting to set (as a default formatsetting) plus the ability to override the default formatsettings through an testcaseattribute overoad

**Comment by fabriciocolombo** [comment] 2015-06-16 16:59
I think this could be solved by enclosing the float values with double quotes, then when split the values take that as one value.

    [TestCase('Test1', '6, "5,44", "0,0001"')]

**Comment by sglienke** [comment] 2015-06-18 09:01
@fabriciocolombo That won't solve anything because this will fail on computers that have the dot as decimal separator.

**Comment by fabriciocolombo** [comment] 2015-06-18 23:40
Yep, about the use of double quotes, it's really useless. The same result is achieved just changing the separator(i missed this option). Then my example could be replaced by:

    [TestCase('Test1', '6| 5,44| 0,0001', '|')]
	
About the difference between development environments, usually the teams are not distributed, and uses the same regional settings, so use a convention is good enough for the most of use cases. If is not the case, them the format settings could be changed globally or per test fixture.

Anyway, we could enforce the use of a separator inside ConvStr2Float, this way:

    function ConvStr2Float(const ASource: TValue; ATarget: PTypeInfo; out AResult: TValue):     Boolean;
    var
      LFormatSettings: TFormatSettings;
      LEnforcedValue: string;
    begin
       ...
        LFormatSettings.DecimalSeparator := '.';
        LEnforcedValue := StringReplace(ASource.AsString, ',', '.', [rfReplaceAll]);
        AResult := TValue.FromFloat(ATarget, StrToFloat(LEnforcedValue, LFormatSettings));
      ...
    end;

This way will work using comma or dot as decimal separator.

WDYT?

**Comment by altembo** [comment] 2015-06-19 07:41
This would work, yes, but I would still prefer some dunitx-wide formatsettings instead of hiding it within some conversion methods. The same goes for converting dates. 
I would try to provide a fix this weekend if we reach an agreement.

**Comment by blackshadowshade** [comment] 2015-10-06 06:25
I'd like to add that I've hit this problem while using DUnitX too, and I thought you might be interested in why.

I live in Australia and develop with a colleague for people all over the world. In the past, we have been bitten by region-specific formatting bugs, so now, I have my development computer set to the regional settings for Spain, while my colleague has his computer set to Australian regional settings. That way, we have more of a chance of catching bugs when we're testing.

Thus, what we need are global DUnitX settings that will work independent of which regional settings are on the local computer.

**Comment by sglienke** [comment] 2015-10-06 16:37
My personal preference would be to hardcode the decimal separator to a dot as Fabricio suggested above because this is also how you write it in code. Since the values passed to the attributes are also compiled into your application that is not something that comes from an external source and needs to support any local settings.

I would also treat TDateTime/TDate/TTime similar (a simple version of ISO 8601 with hardcoded formatsettings) - which are also handled by ConvStr2Float.

Anything else imho is just unnecessary flexibility for the sake of flexibility without any value - more so the opposite because then your settings set somewhere have to match the values passed by the attributes. If you share your test code (imagine you report a bug somewhere and provide them an easy to reproduce test case) you also need to share your format settings.

**Comment by mWaltari** [comment] 2015-10-18 12:33
Got hit by this with first try of DUnitX :) I would prefer it to use dot as decimal separator, same way as the Compiler expects it to be written. 

When this is fixed can I update it to IDE with GetIT?

**Comment by vincentparrett** [comment] 2015-10-18 22:51
I'm going to go with fabriciocolombo & sglienke here and hard code it to use . - as pointed out, when you write floating point numbers in code you use . and since we're using attributes the values are known at compile time. To change this to use a global level setting would require a lot of work to revisit every bit of code for opportunities to use the global formatsettings.. not something I have time for. 

As for GetIt, that's embarcadero's baby, I have nothing to do with it, and don't plan on supporting it (I would if they had created a proper package manager).

**Comment by vincentparrett** [comment] 2015-10-18 22:54
Closing, merged into master.

**Closed by vincentparrett** 2015-10-18 22:54 UTC

**Comment by codejanovic** [comment] 2015-10-23 09:14
thanks vincent.
